"""
Django settings for webchecklist project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path

# Base directory of the project
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - not suitable for production
# Keep the secret key confidential in production environments
SECRET_KEY = 'django-insecure-53ousp#tlm!v#ee-07njbaorx7jy(c-(q*m0b$cabn8&(-$q#u'

# Debug mode: should be set to False in production
DEBUG = True

# Hosts allowed to access the application
ALLOWED_HOSTS = []

# Installed apps include both built-in and third-party apps
INSTALLED_APPS = [
    # Default Django apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Your custom app
    'secureapp',

    # Third-party apps for forms and authentication
    'crispy_forms',
    'crispy_bootstrap5',
    'django_recaptcha',
    'django_otp',
    'django_otp.plugins.otp_static',  # Static OTP tokens for 2FA
    'django_otp.plugins.otp_totp',    # Time-based OTP tokens for 2FA
    'two_factor',                     # Two-factor authentication
]

# Crispy Forms configuration
CRISPY_ALLOWED_TEMPLATE_PACKS = 'bootstrap5'
CRISPY_TEMPLATE_PACK = 'bootstrap5'

# Google reCAPTCHA configuration
RECAPTCHA_PUBLIC_KEY = '6LfWFb4qAAAAACfs430jUNpC3j2eTKAXf8ItRMVc'
RECAPTCHA_PRIVATE_KEY = '6LfWFb4qAAAAAET6_ejgqkpgMK66a_74s4hYDrD9'

# Two-factor authentication login configuration
LOGIN_URL = 'two_factor:login'  # Redirect users to 2FA login page
LOGIN_REDIRECT_URL = 'dashboard'  # Redirect after successful login

# Trusted origins for CSRF protection
CSRF_TRUSTED_ORIGINS = [
    'https://8000-cs-61983882132-default.cs-us-central1-pits.cloudshell.dev'
]

# Middleware for handling requests and responses
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django_otp.middleware.OTPMiddleware',  # Middleware for 2FA
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Root URL configuration
ROOT_URLCONF = 'webchecklist.urls'

# Template configuration for rendering HTML
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # Add custom template directories here
        'APP_DIRS': True,  # Look for templates inside app directories
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # Required for Crispy Forms
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# WSGI application for deploying the project
WSGI_APPLICATION = 'webchecklist.wsgi.application'

# Database configuration using SQLite
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # SQLite as the database engine
        'NAME': BASE_DIR / 'db.sqlite3',  # Database file location
    }
}

# Password validation settings for security
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Localization settings
LANGUAGE_CODE = 'en-us'  # Language code for the application
TIME_ZONE = 'America/Mexico_City'  # Time zone for Mexico City
USE_I18N = True  # Enable internationalization
USE_TZ = True  # Use timezone-aware datetimes

# Static files (CSS, JavaScript, Images)
STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']  # Path to static files

# Default auto field for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
